### ISSUE TITLE
specify the type of contributor

### ISSUE THREAD

**Issue by iamruhul** [devsonket/devsonket.github.io#102]
Look at this picture below

![devsonket com_shortcut-chrome-win](https://user-images.githubusercontent.com/31810947/49350767-77eb1a80-f6da-11e8-900a-175fcb2eb63b.png)

At the top.. it says contributor... looking at the picture it's not certain what kind of contribution they did. It would be better if it says something like - **Cheatsheet contributor**

**Comment by iamruhul** [comment]
Now no matter how much i contribute to the codebase, my picture won't show up there. There should be two type of contributor - one contributing on cheetsheet and the other one  on codebase.

**Comment by iamruhul** [comment]
@zonayedpca  you could wright something like ... "**written by**" to be more specific instead of "**contributor**"

**Comment by zonayedpca** [comment]
I think the position of this section specifies what type of contributors they are...

**Comment by iamruhul** [comment]
maybe... btw I am thinking about a **credit page**..

**Comment by iamruhul** [comment]
That could come in handy for us contributors.. what's ur thought??
