### ISSUE TITLE
I can help you fix your README

### ISSUE THREAD

**Issue by Vishal-Kamath** [devsonket/devsonket.github.io#1037]
README's are an essential tool when it comes to communicating your ideology with other programmers and helping them understand your project. I am assuming that you are a Bengali native developer and want to help others overcome the language barrier when it comes to programming. 
I went through your readme file; it had broken links, grammatical errors, and formatting issues. I know that a code base is sacred to every developer and if you don't mind I will be happy to help better format your README into the English language 😊.

**Comment by Vishal-Kamath** [comment]
I have created a pull request but somehow I messed up linking it to this issue. The pull request ID is #1038

**Comment by saifscripts** [comment]
There are still some formatting issues in the documentation. In some section, Bengali and English versions are mixed. I want to fix these issues. Please, assign me to this issue.

**Comment by saifscripts** [comment]
I've made changes to fix the documentation issues. Please check them out. If it's good, I'm ready to make more improvements. Your feedback is important. Thanks in advance!
