### ISSUE TITLE
Fix django cheatsheet

### ISSUE THREAD

**Issue by arasad28** [devsonket/devsonket.github.io#1094]
I just fix a django cheatsheet issue and further I was planning to contribute by added some cheatsheet on django. But Netlify shows the error while building. Don't know what the problem, I just edit a line and fix the errors. If anyone help with this issue, it will be helpful for my future contribution.

**Comment by ihasidul** [comment]
Did you try to build the project locally?

**Comment by arasad28** [comment]
> Did you try to build the project locally?

no. I just change a minor issue. Why found this build error didn't know.
