### ISSUE TITLE
Javascripy

### ISSUE THREAD

**Issue by shoriful-stack** [devsonket/devsonket.github.io#1103]
কি কি চান বিস্তারিত লিখুন

**Comment by shoriful-stack** [comment]
Basic fundamental

**Comment by shaonkabir8** [comment]
প্রয়োজনীয় `টপিক` ছাড়া `ইস্যু` এবং একই নামের একাধিক `ইস্যু` না তৈরী করার জন্য অনুরোধ করছি। 

ধন্যবাদ।
