### ISSUE TITLE
Request: Cheatsheet for markdown.

### ISSUE THREAD

**Issue by AnikHasibul** [devsonket/devsonket.github.io#144]
^_^

**Comment by shabab477** [comment]
Hi, thanks for the request for a new cheatsheet. Are you interested in writing it?

**Comment by AnikHasibul** [comment]
> Are you interested in writing it?

Is there any friendly data entry system or simple json generator for this?

**Comment by shabab477** [comment]
Not as of now. We have that as a feature request at #53 but unfortunately I am not able to find enough time to build one? Do you want to have a go at it?

**Comment by zonayedpca** [comment]
Added to our list
