### ISSUE TITLE
Can I add `Vagrant` commands cheat sheet?

### ISSUE THREAD

**Issue by jamal-pb95** [devsonket/devsonket.github.io#149]

**Comment by zonayedpca** [comment]
Of course brother...

**Comment by jamal-pb95** [comment]
Thanks, @zonayedpca bhai, I'll raise a PR soon... Inshallah

**Comment by jamal-pb95** [comment]
@zonayedpca bhai, [#150 PR](https://github.com/devsonket/devsonket.github.io/pull/150) has been raised by me. Please take a look and take the necessary step. thanks
