### ISSUE TITLE
Use tools like prettier and eslint to make code style consistent

### ISSUE THREAD

**Issue by ruhulwebdev** [devsonket/devsonket.github.io#15]
Consider using prettier + eslint to make code style consistent across all the contributors. Otherwise we'll have to deal with a thousand different code style...

**Comment by zonayedpca** [comment]
I think we should include something like this with our project so that everyone can have the same style. I don't have enough knowledge about them. Prettier ESLint might be a good solution, but still, I am not. Please let us know what do you think...

**Comment by iamruhul** [comment]
yeah prettier and eslint the go to solution nowadays.. so that's a good starting point

**Comment by iamruhul** [comment]
@zonayedpca  CRA already includes an amazing eslint config by default - [eslint-config-react-app](https://www.npmjs.com/package/eslint-config-react-app)... so that might be considerable...

**Comment by iamruhul** [comment]
this links could be useful
...
[a medium post](https://medium.freecodecamp.org/integrating-prettier-with-eslint-and-stylelint-99e74fede33f)

[prettier official site](https://prettier.io/docs/en/eslint.html)
