### ISSUE TITLE
want to add Pandas Dataframe. [python library for data science]

### ISSUE THREAD

**Issue by jabertuhin** [devsonket/devsonket.github.io#153]
Wanted to add few functions of "pandas" dataframe. Should I add those in python section?

**Comment by shabab477** [comment]
Yeah sure go ahead.

**Comment by zonayedpca** [comment]
Any update brother?

**Comment by jabertuhin** [comment]
I have started working on it. Added the necessary code components. Struggling to express few of them in Bangla :3 
Never thought of this situation.

**Comment by zonayedpca** [comment]
Please use popular words even if they are in English so that everyone can understand... Also, note that, try to write those English words using Bengali characters. That will help you. Thanks 👍

**Comment by shabab477** [comment]
Resolved #186
