### ISSUE TITLE
add HOWTOCONTRIBUTE.md 

### ISSUE THREAD

**Issue by jabertuhin** [devsonket/devsonket.github.io#187]
Can we have an instruction for how to contribute?
Like - fork 1st then clone,  create branch of certain name etc.
This can help people to contribute in a specific way and who are new to collaboration. We can add an existing article or can add one in Bangla.

**Comment by dibakarsutradhar** [comment]
Hey! We already have it in Bangla. It's written on the main repository documentation. Please follow this link for clear instruction on How to contribute in Bangla - https://github.com/devsonket/devsonket.github.io

Hope this helps. Thanks.

**Comment by jabertuhin** [comment]
I was talking about something like this - https://www.freecodecamp.org/news/a-simple-git-guide-and-cheat-sheet-for-open-source-contributors/

**Comment by zonayedpca** [comment]
If you're willing to write any posts regarding this thing, we will add a reference to it so that interested people can learn something and also start contributing here. We'll really appreciate it if you do this for Devsonket.

**Comment by zonayedpca** [comment]
This issue seems to be inactive for a long time. We're closing this one. Feel free to reopen this issue if you want... Thanks for being with us.
