### ISSUE TITLE
Multiple OS keyboard shortcuts feature 

### ISSUE THREAD

**Issue by imalisiddique** [devsonket/devsonket.github.io#188]
Multiple OS keyboard shortcuts like macOS, Windows, and Linux
![AwesomeScreenshot-Default-keyboard-shortcuts-for-Illustrator-2019-07-19-13-07-27](https://user-images.githubusercontent.com/4035727/61515900-86960000-aa25-11e9-8f39-a9744086790e.png)

**Comment by zonayedpca** [comment]
I like your idea. I think we should add another format of cheatsheet suitable for Shortcuts type of cheatsheets.

**Comment by zonayedpca** [comment]
This issue seems to be inactive for a long time. We're closing this one. Feel free to reopen this issue if you want... Thanks for being with us.
