### ISSUE TITLE
কিসের চিটশীট চান?

### ISSUE THREAD

**Issue by devmmhs** [devsonket/devsonket.github.io#202]
SCSS or SASS সম্পর্কিত ।
ইউ আই ইউএক্স সম্পর্কিত ।

**Comment by zonayedpca** [comment]
আমাদের কন্ট্রিবিউটররা চেষ্টা করবে এই সম্পর্কিত চিটশিট অ্যাড করার জন্যে... আমাদের লিস্টে হাই প্রায়োরিটি হিসেবে থাকবে...

**Comment by imalisiddique** [comment]
ইউ আই/ইউএক্স চিটশীট বলতে?

**Comment by zonayedpca** [comment]
অবশ্যই ভাই, আপনি করতে পারেন... আপনি করতে চাইলে আমি এখানে আপনাকে টাস্ক অ্যাসাইন করে দিচ্ছি... কনফার্মেশন দিলে অ্যাসাইন করে দিব 👍

**Comment by imalisiddique** [comment]
ok

**Comment by zonayedpca** [comment]
যখন এই টপিকের উপর পুল রিকোয়েস্ট দিবেন, অবশ্যই এই ইস্যুটাকে রেফার করে দিবেন... ধন্যবাদ আপনাদের প্রচেষ্টার জন্য 💯

**Comment by Revel109** [comment]
@zonayedpca here is the pr for pm2 cheatsheet: https://github.com/devsonket/devsonket.github.io/pull/204

**Comment by zonayedpca** [comment]
Cheat sheets are up already... I am closing this issue right now... If you want more, try to be more specific...
