### ISSUE TITLE
Formatting Linux command-line cheatsheet

### ISSUE THREAD

**Issue by selectiveduplicate** [devsonket/devsonket.github.io#21]
I'm just opening this as an "issue" for discussion. I suggest that we format and break down the Linux command-line cheatsheet into a couple of "sections", like:

- System information
- Hardware information
- File and directory commands
- User management
- Compression/working with compressed files
and so on.

I'm expecting thoughts and comments... :slightly_smiling_face:

**Comment by jamal-pb95** [comment]
@selectiveduplicate Good idea man!

**Comment by zonayedpca** [comment]
Good Idea Brother... If you can update them, please do the update... Otherwise, I hope someone else will update that... 👍

**Comment by selectiveduplicate** [comment]
Okay I'll start working on it.
I'll be a bit busy but hope to commit by Monday.

**Comment by dibakarsutradhar** [comment]
Good Idea Brother !
