### ISSUE TITLE
জাভাস্ক্রিপ্ট মডিউল নিয়ে একটা চিটশিট অ্যাড করতে চাচ্ছি।

### ISSUE THREAD

**Issue by jamal-pb95** [devsonket/devsonket.github.io#243]
@zonayedpca ভাই, জাভাস্ক্রিপ্ট মডিউল নিয়ে একটা চিটশিট অ্যাড করতে চাচ্ছি।

**Comment by zonayedpca** [comment]
অবশ্যই ভাই...

**Comment by jamal-pb95** [comment]
thanks for your positive response. here is my PR #244
