### ISSUE TITLE
Cheat Sheet on C#

### ISSUE THREAD

**Issue by jabertuhin** [devsonket/devsonket.github.io#248]
I will be working on creating cheat sheet for c#.

**Comment by maacpiash** [comment]
Please start, bhai. I would love to help 😀

**Comment by zonayedpca** [comment]
Of course, we are eagerly waiting for your contribution

**Comment by zonayedpca** [comment]
ভাই আপনার পুল রিকোয়েস্ট #251 এ কিছু পরিবর্তনের জন্য রিকোয়েস্ট করা হয়েছে... প্লীজ পরিবর্তন করে আবার পুশ করেন আরেকটা...
