### ISSUE TITLE
BugFix

### ISSUE THREAD

**Issue by jabertuhin** [devsonket/devsonket.github.io#26]
![bugfix](https://user-images.githubusercontent.com/22750032/48669544-f10e3d80-eb30-11e8-851d-d99e58efafbb.png)

This needs to be fixed in both "জাভা প্রোগ্রামিং" and "সি প্রোগ্রামিং টুকিটাকি".

**Comment by dibakarsutradhar** [comment]
ধন্যবাদ বাগ ধরিয়ে দেয়ার জন্য। খুব শীঘ্রই এটার সমাধান করা হবে।

**Comment by dibakarsutradhar** [comment]
সমস্যা সমাধান করা হয়েছে।
