### ISSUE TITLE
Docker container cheatsheet minor modify

### ISSUE THREAD

**Issue by morshadunnur** [devsonket/devsonket.github.io#281]
List of all ডকার কন্টেইনার, even not running
* docker ls -a is not a command
I think docker container commands need to be specified like - 
=> docker container ls -a
=> docker container list -a
=> docker container ps -a

Because,  docker ps  and docker ps -a to check container process 
Thanks

**Comment by zonayedpca** [comment]
We are requesting you to send a PR with the correction. Also, refer to this issue if you are doing that...

**Comment by morshadunnur** [comment]
> We are requesting you to send a PR with the correction. Also, refer to this issue if you are doing that...

I made a PR. I was sick.
Thank you so much.

**Comment by zonayedpca** [comment]
Thank you brother...
