### ISSUE TITLE
Add example for commands (Feature request)

### ISSUE THREAD

**Issue by Hasnayeen** [devsonket/devsonket.github.io#30]
It'll be a nice addition to have example for corresponding commands. For example in linux command page when a command is clicked a modal can be open with example of using that bash command.

**Comment by dibakarsutradhar** [comment]
Thanks for the suggestion. We'll sure work on this matter all together. 
@zonayedpca  Look into this suggestion.

**Comment by zonayedpca** [comment]
We are still in trouble with multiline code... Hope we'll figure this out soon... If anyone can help **devsonket** with this problem, please make a PR or discuss it with us so that we can solve the problem.

**Comment by dibakarsutradhar** [comment]
It’s possible to achieve in current system by using ‘/n’ newline command on the code.

**Comment by iamruhul** [comment]
working on it (:

**Comment by iamruhul** [comment]
This issue is related to issue #68 ... That will solve this issue inshallah.
