### ISSUE TITLE
I would love to add a cheat sheet for Axios

### ISSUE THREAD

**Issue by Geektrovert** [devsonket/devsonket.github.io#310]

**Comment by zonayedpca** [comment]
Sure, you can... Please...

**Comment by shaonkabir8** [comment]
@Geektrovert, Have you started yet ?
I'm curious to add `axios` cheat-sheet. let's do it together.

**Comment by Geektrovert** [comment]
@shaonkabir8, sorry for the late response. Thank you for your interest to contribute, it'd be really great! I compiled some cheats randomly, but I haven't written any code yet. I will make a PR soon. And sure, let's work together!

**Comment by shaonkabir8** [comment]
@Geektrovert , It'd be amazing mate.❤
Take time and make a `pull request ` with your initial cheat sheet. I'll be there to contribute  if needed 😘

**Comment by jabertuhin** [comment]
@Geektrovert Hi.
I have a feedback regarding your issue title. Can you fix the typo "cheetshit" to "cheat sheet"?

**Comment by princerafid01** [comment]
@Geektrovert Any progress ? :)

**Comment by Geektrovert** [comment]
@princerafid01 nah bhai. I forgot about it. You can work on this if you want to!

**Comment by zonayedpca** [comment]
Please someone go ahead... We badly need a cheatsheet on axios... Thanks... :)

**Comment by sabbirshawon** [comment]
Start this first then anyone can contribute

**Comment by imovishek** [comment]
@princerafid01 have you started this yet? If not, I talked with @Geektrovert and am willing to start this as soon as possible.

**Comment by princerafid01** [comment]
@ovis96 I have not started yet.  You can start.

**Comment by HridoyHazard** [comment]
Added Axios Data Cheatsheet 
Here Is The Pr #628
