### ISSUE TITLE
Django

### ISSUE THREAD

**Issue by Revel109** [devsonket/devsonket.github.io#34]
It would be great if we have the Django-cheatsheet. If needed I can contribute.

**Comment by zonayedpca** [comment]
Sure, brother... We want your contribution... 👍 If you need any help, then you can discuss with us... We are looking forward to your contribution...

**Comment by Revel109** [comment]
OK. I have free time at weekends. I will manage time for this. Will Let you know If I do face any issue.

**Comment by Revel109** [comment]
Yes, I have started the flow. I was sick, that's why it became a bit slow to start. I will contact with @zonayedpca if i have any issue.

**Comment by zonayedpca** [comment]
Any update brother?

**Comment by Revel109** [comment]
Completed almost 50%. Rest part will be done by this week hope so. Couldn't manage enough time for this.
Is there anyone who is interested to complete this with me?

**Comment by zonayedpca** [comment]
This issue seems to be inactive for a long time. We're closing this one. Feel free to reopen this issue if you want... Thanks for being with us.
