### ISSUE TITLE
Any plans for Hacktoberfest?

### ISSUE THREAD

**Issue by shabab477** [devsonket/devsonket.github.io#343]
October is the month when devs all over the world celebrate the spirit of Open Source projects with [Hacktoberfest](https://hacktoberfest.digitalocean.com/). Are there any plans to add small proposals for this event? 

Probable proposals for implementing Hacktoberfest:
- Propose unique cheat sheets
- Issue Small UI/UX features
- Propose guides or tutorials in Bengali for using GIT
- Add label named `hacktoberfest`

Thanks.

**Comment by zonayedpca** [comment]
Sorry for the late reply. Yes, we surely can start. It would be great if you could take the responsibility to implement this event.
