### ISSUE TITLE
ইমোজি চিটশিট যোগ করতে চাই

### ISSUE THREAD

**Issue by shaonkabir8** [devsonket/devsonket.github.io#353]
মার্কডাউন লেখার সময় বা নিত্যদিনের বহুকাজেই আমরা ইমোজি ব্যবহার করি।
ডেভসংকেত এ ইমোজি নিয়ে কোন চিটশিট নেই 😭

আমি 'ইমোজি' চিটশিট যোগ করতে আগ্রহী।

**Comment by zonayedpca** [comment]
অবশ্যই শুরু করুন... যদি ইমোজি সাপোর্ট না থেকে থাকে, তাহলে আমরা শীগ্রই অ্যাড করে নিবো... আপনি কাজ শুরু করে দিন... ধন্যবাদ

**Comment by shaonkabir8** [comment]
জ্বী ভাই। আমি শুরু করেছি।

কোড ফরম্যাট এইভাবে লিখছিঃ

```js
"contents": [
    {
      "title": "ইমোজি ক্যাটাগরির নাম ",
      "items": [
        {
          "definition": "👋"
          "code": ":wave:"
        },
        {
          "definition": "😎",
          "code": ":sunglasses:"
        }
      ]
    }
]


```

**Comment by zonayedpca** [comment]
Yes perfect!

**Comment by shaonkabir8** [comment]
### :rocket: আপডেটঃ
:heavy_check_mark: ইমোজি চিটশিট যোগ করা হয়েছে।
