### ISSUE TITLE
Google Analytics for gh-page 

### ISSUE THREAD

**Issue by shabab477** [devsonket/devsonket.github.io#4]
I think we can have a google analytics setup for monitoring web traffic. This should help us decide suitable sponsor in the future.  Probably a feature request that can be considered.

**Comment by zonayedpca** [comment]
Good idea brother... If you can help **devsonket** with that, it would be great...

**Comment by selectiveduplicate** [comment]
@zonayedpca If GA is planned to be added, I think you're gonna have to do it from your end because it will require the "orignal" website URL, plus you're gonna have to sign up and get a "tracker ID" and "tracker script", which can be loaded via the ``index.html``.

**Comment by zonayedpca** [comment]
Do you think we should add GA? Please vote for GA...

**Comment by selectiveduplicate** [comment]
> Do you think we should add Google Analytics? Please vote for Google Analytics... And also tell us why we should add this thing. I am personally don't know anything about it. Github itself has something called Insights. Isn't it enough?

I myself am pretty unfamiliar to GA, but basically it gives you statistics about the visitors that visit your site, how they use it etc; pretty much an advanced version of what you see in a Blogger blog.
