### ISSUE TITLE
সমস্যা

### ISSUE THREAD

**Issue by shuvo-sutradhar** [devsonket/devsonket.github.io#42]
লারাভেল পিএইচপি ফ্রেমওয়ার্কে,  টেবিল গুলো মুছে ফেলে নতুন করে টেবিল তৈরি করতে চাইলে যেই কমান্ড
 দেওয়া হয়েছে সেটা মনে হয় php artisan migrate:reset এর পরিবর্তে php artisan migrate:refresh হবে ।

**Comment by zonayedpca** [comment]
ধন্যবাদ ভাই... আপনি শিউর হলে একটা পুল রিকোয়েস্ট দিতে পারেন... অথবা যেকেউ যদি শিউর থাকেন তাহলে দয়া করে পুল রিকোয়েস্ট, অথবা এখানে জানাবেন... আমি ব্যক্তিগতভাবে লারাভেল নিয়ে কাজ করি না, তাই আমার ধারণা নাই...

**Comment by iamruhul** [comment]
# It will be  `php artisan migrate:fresh` actually... 

![screenshot from 2018-11-21 11-50-41](https://user-images.githubusercontent.com/31810947/48821543-f3b4a100-ed83-11e8-8f62-06749df1a33e.png)

**Comment by shuvo-sutradhar** [comment]
Thanks.
I  was talking about rollback and migrate.
