### ISSUE TITLE
সি প্রোগ্রামিং এ গাণিতিক বিল্ট ইন ফাংশন কারেকশন

### ISSUE THREAD

**Issue by n0man-ch0wdhury** [devsonket/devsonket.github.io#423]
"y এর পাওয়ার হিসেবে x কে নেয়ার জন্য" এর জন্য pow(x, y) এর স্থলে pow(y, x) হবে সম্ভবত। যেহেতু pow(base, power) হয়।

**Comment by kailash360** [comment]
আমি এই ইস্যুতে কাজ করতে চাই |

**Comment by kailash360** [comment]
আমি এই ইস্যুতে কাজ করতে চাই |

**Comment by kailash360** [comment]
আমি এই জন্য একটি PR #532  তৈরি করেছি

**Comment by kailash360** [comment]
If the issue is fixed, kindly close it

**Comment by shaonkabir8** [comment]
Hey [Mate](@kailash360 ) :wave: 
Great Job. Thanks for your contribution on Devsonket. The Isssue is closed successfully with this PR #532 

- Shaon Kabir <shaonkabir8>
