### ISSUE TITLE
ডেভসংকেত এর জন্য প্রোজেক্ট মেইন্টেইনার দরকার 

### ISSUE THREAD

**Issue by zonayedpca** [devsonket/devsonket.github.io#430]
বর্তমান রিপো অ্যাডমিন, রাইটার, মেইন্টেইনাররা বেশী ব্যস্ত থাকায় ঠিকমতো পুল রিকোয়েস্ট চেক করা থেকে শুরু করে যাবতীয় ব্যাপারগুলো দেখাশোনা করতে বেশ সমস্যা, দেরী হচ্ছে। তাই আমরা ৩ জন মেইন্টেইনার নেওয়ার পরিকল্পনা করেছি। যারা যারা আগ্রহী তাঁরা নিজে কমেন্ট করতে পারেন বিস্তারিত কিছু ইনফরমেশন দিয়েঃ
- ওপেন সোর্স কোনো প্রোজেক্টে কন্ট্রিবিউট করেছেন কিনা? একাধিক কন্ট্রিবিউশন করে থাকলে আপনার কাছে কোন কন্ট্রিবিউশনটা গর্বের মনে হয়? 
- আপনার বর্তমান স্কিলসেট ও কিছু ব্যক্তিগত তথ্য(কোথায় চাকুরী করছেন, কিসে পড়াশোনা করছেন ইত্যাদি ইত্যাদি)
- ডেভসংকেত নিয়ে আপনার ভবিষ্যৎ চিন্তা কি? 

এখানে সবচেয়ে গুরুত্বপূর্ণ বিষয় হচ্ছে আপনাকে অন্তত একটা ওপেন সোর্স প্রোজেক্টে কন্ট্রিবিউট করার অভিজ্ঞতা থাকতে হবে। বেশী অভিজ্ঞদের প্রায়োরিটি দেওয়া হবে।

**Comment by sabbirshawon** [comment]
@zonayedpca bhai আমি আগ্রহী আছি,

**Comment by zonayedpca** [comment]
> @zonayedpca bhai আমি আগ্রহী আছি,

ভাই ডিটেইলস লিখে কমেন্ট করুন, তাহলে সবার জন্য ভালো হবে...

**Comment by sabbirshawon** [comment]
> > @zonayedpca bhai আমি আগ্রহী আছি,
> 
> ভাই ডিটেইলস লিখে কমেন্ট করুন, তাহলে সবার জন্য ভালো হবে...

- ওপেন সোর্স প্রজেক্টে কন্ট্রিবিউট করেছি তার মধ্যে ডেভসংকেত, কয়েকটি রিয়েক্ট+নোড জেএস এর প্রজেক্ট রয়েছে কিন্তু সবার সাথে ডেভসঙ্কেতের কন্ট্রিবিউশনটা ভালো লেগেছে বেশি
- বর্তমানে রিএক্ট নিয়ে কাজ করি পাশাপাশি সিলেটের একটি কোম্পানিতে(ডিজিটা ইন্টারেক্টিভ) জব করতেছই দীর্ঘ ২বছর থেকে

**Comment by shaonkabir8** [comment]
আমি শাওন কবির, Code Eating Ants টিমে ফ্রন্টেন্ড ডেভলপার হিসাবে আছি এক বছরের বেশি সময় ধরে  :heart:

আমার ওপেন সোর্স কন্ট্রিবিউশনের একটা বড় অংশ জুড়ে আছে ডেভসংকেত পরিবার। 

ডেভসংকেতে আমার উল্লেখযোগ্য কন্ট্রিবিউশনঃ 
- ইয়ার্ন চিটশিট
- ইমোজি চিটশিট
- প্রভাত কিবোর্ড চিটশিট 


ডেভসংকেত এর মেইন্টেইনার হওয়ার জন্য আমি আগ্রহী  :rocket:

**Comment by iamraufu** [comment]
আসসালামু আলাইকুম ভাই,

গতকাল রাতে  লিঙ্কড ইন এ আপনার সাথে এ ব্যাপারে কথা হয়েছিল ভাই । আমি ইফতিখার রহমান, বর্তমানে ব্রাক বিশ্ববিদ্যালয়ের সিএসসি ডিপার্টমেন্ট এ শেষ বর্ষের পড়াশুনা সম্পন্ন করছি । 

পড়াশুনার পাশাপাশি রিয়েক্ট জেএস + নোড জে এস এর বিভিন্ন প্রোজেক্ট এ কাজ করার অভিজ্ঞতা রয়েছে । এছাড়াও জাভা, পাইথন, মাইসিকুইল সহ আরো অনেক প্রোগ্রামিং ভাষার দক্ষতা রয়েছে ।  ওপেন সোর্স প্রজেক্টে কন্ট্রিবিউট এর মধ্যে সবার সাথে ডেভসঙ্কেতের কন্ট্রিবিউশনটা বেশি ভালো লেগেছে এবং কন্ট্রিবিউশনটা গর্বের ।

ডেভসংকেত নিয়ে আমার ভবিষ্যৎ চিন্তা হচ্ছে ডেভসংকেত কে বাংলা চিটশিটের ভান্ডার এ রূপান্তর করা ।

**Comment by ahmubashshir** [comment]
### উল্লেখযোগ্য কন্ট্রিবিউশন:
 * z411/trackma#498
 * phuhl/linux_notification_center#125
 * OpenBangla/OpenBangla-Keyboard#227
 * anbox/anbox#1755

### পড়াশোনা ও স্কিলসেট
 * এইচএসসি ২০২১ ব্যাচ(পরীক্ষার্থী)
 * স্কিল: C++, Vanilla JS, Python, GTK+ 3,Git CLI, Shell(Posix SH, Bash, Zsh)

### ডেভসংকেত নিয়ে চিন্তা:
 * অন্যান্য ডাটা সিরিয়ালাইজেশন ফরম্যাট(yaml, toml, ...) সাপোর্ট যোগ করা ও json এ কনভার্ট করার টুল রাখা।
 * গুরুত্বপূর্ণ কমান্ড লাইন টুল(dd, curl, wget, awk, sed, ...) এর চিটশিট গুলো যোগ করা

**Comment by Abu-Zakaria** [comment]
আমি জাকারিয়া.. একজন Web Developer. আমি ৪ বছর ধরে Web Development নিয়ে কাজ করছি
devsonket-এ আমি কিছু contribution করেছি. আরো contribution করার ইচ্ছা আছে
আমি devsonket-এর maintainer হইতে ইচ্ছুক
