### ISSUE TITLE
Developer slack URL doesn't work

### ISSUE THREAD

**Issue by FahimFBA** [devsonket/devsonket.github.io#440]
The link mentioned as the Developer slack is no longer active.

**Comment by fahimfaisaal** [comment]
জি ভাই, স্লাক গ্রুপে আড হইতে পারলে অনেক ভাল হইত। 🙂

**Comment by zonayedpca** [comment]
We have planned to continue our community discussion on our [Facebook Group](https://www.facebook.com/groups/devsonket). Will remove that slack link soon...
