### ISSUE TITLE
📝 HTTP Status Code এর উপর Cheat Sheet বানাতে চাচ্ছিলাম

### ISSUE THREAD

**Issue by iamraufu** [devsonket/devsonket.github.io#475]

**Comment by zonayedpca** [comment]
আমার মনে হয় আমাদের এই টপিকের উপর আমাদের কোনো চিটশিট নেই, এবং এটা খুবই জরুরী... যদি সম্ভব হয় তাহলে প্লীজ শুরু করুন...

**Comment by iamraufu** [comment]
### প্রিয় জুনায়েদ ভাই, 

**ধৈর্য ধারণের জন্য অসংখ্য ধন্যবাদ । কিছু ব্যাক্তিগত কারণে বিলম্ব হয়েছে । তদুপরি, চিটশিট এড করে পুল রিকুয়েস্ট দিয়েছি ।**

**Comment by shaonkabir8** [comment]
Hi mate :wave: 
Thanks for your valuable contribution on HTTP Status Code.

Hopefully this [PR - #479](#479) has already solved this issue.
