### ISSUE TITLE
javascript

### ISSUE THREAD

**Issue by khanfaysal** [devsonket/devsonket.github.io#478]
modern javascript syntax and use case shortly.

**Comment by sabbirshawon** [comment]
Do you want to contribute to Modern JS Syntax? @khanfaysal

**Comment by khanfaysal** [comment]
No but you add my proposal Because it is to be useful for others junior js programmer.

**Comment by sabbirshawon** [comment]
so make it and send PR

**Comment by iamraufu** [comment]
Dear @khanfaysal what's the update?

**Comment by shaonkabir8** [comment]
Hi mate :wave: 
Thanks for your interest and participation on contributing to `Devsonket` on `Modern JavaScript Syntax`.
I'm linking a valid PR which has already been merged.
Check #302 for this scenario. . Hopefully It'll help to close this issue :fire: 

Stay connected with `Devsonket Family` :heart:
