### ISSUE TITLE
Python 3 চিট শীটে Loops এবং Conditionals(If-Else) অনুপস্থিত |

### ISSUE THREAD

**Issue by kailash360** [devsonket/devsonket.github.io#491]
Python 3 চিট শীটে for-loop, while-loop, if-else-conditionals অনুপস্থিত। আমি তাদের কোডে যুক্ত করতে চাই।

**Comment by zonayedpca** [comment]
অবশ্যই... আমি আপনাকে অ্যাসাইন করে দিলাম... দয়া করে পুল রিকোয়েস্ট দেওয়ার সময় এই ইস্যুটা মেনশন করে দিবেন... ধন্যবাদ...

**Comment by kailash360** [comment]
Pull request has been made
