### ISSUE TITLE
Add link sharing feature on cheat sheet blocks

### ISSUE THREAD

**Issue by shabab477** [devsonket/devsonket.github.io#50]
I want a small copy link button that copies anchor link to a particular cheat sheet block and be easily shareable by just pasting it and sending to someone.

**Comment by iamruhul** [comment]
what d u mean by " a particular cheat sheet block"??

**Comment by iamruhul** [comment]
right now.. you can only get the page url.. but i'm guessing you want each portion/block to have a url 
like `#section` to copy ???

**Comment by shabab477** [comment]
Yes the description of the issue is pretty much self-explanatory. It should have something like a shareable anchor link to a particular cheat sheet block.

**Comment by zonayedpca** [comment]
Are we looking for this thing? 
![image](https://user-images.githubusercontent.com/18544717/49066387-f103f100-f246-11e8-8e13-9b5b4b8363e0.png)
Also, tell me which link will be better, 
- In this case, I am using the title as the link(like ```/shortcut-chrome-win#উইন্ডো-এবং-ট্যাব-ম্যানেজ```)
Remember this link will show up much longer than it is like this one:
```
https://devsonket.github.io/shortcut-chrome-win#%E0%A6%89%E0%A6%87%E0%A6%A8%E0%A7%8D%E0%A6%A1%E0%A7%8B-%E0%A6%8F%E0%A6%AC%E0%A6%82-%E0%A6%9F%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%AC-%E0%A6%AE%E0%A7%8D%E0%A6%AF%E0%A6%BE%E0%A6%A8%E0%A7%87%E0%A6%9C
```
- Or should I go for a more simple link, like ```/shortcut-chrome-win#3```

**Comment by shabab477** [comment]
`/shortcut-chrome-win#3` is a much friendlier url.
