### ISSUE TITLE
কিসের চিটশীট চান?

### ISSUE THREAD

**Issue by jamintowebdev** [devsonket/devsonket.github.io#509]
Please, Kindly upload JavaScript Cheetsheet. Thank you so much.

**Comment by shaonkabir8** [comment]
Hi  mate :wave: 
Cheat sheet for `JavaScript` has already added. 
Our Contributors will contribute later on :boom: 
Stay connected with `Devsonket Family` :fire: 

Best regards,
Shaon Kabir
project maintainer, Devsonket
