### ISSUE TITLE
api link

### ISSUE THREAD

**Issue by Russell-mahmud** [devsonket/devsonket.github.io#518]
কি কি চান বিস্তারিত লিখুন

**Comment by sabbirshawon** [comment]
api link দিয়ে কি বুঝাচ্ছেন বিস্তারিত লিখে পোস্ট করুন @Russell-mahmud

**Comment by Russell-mahmud** [comment]
bujhlam naaaaaaa

**Comment by sabbirshawon** [comment]
এই issue টা কিসের জন্য তাই বললাম।

**Comment by shaonkabir8** [comment]
HI [mate](@Russell-mahmud ) :wave: 
Before creating any issues or sending PR, make sure to write a brief explanation on which your're contributing.
It's much more easier for maintainers & contributors to understand what's going on actually.

Thanks and Regards,
Shaon Kabir

**Comment by Russell-mahmud** [comment]
eita diye ki ki kora jabe?
