### ISSUE TITLE
কিসের চিটশীট চান? -> Rust programming language

### ISSUE THREAD

**Issue by notun-manush** [devsonket/devsonket.github.io#523]
basics,all new features of rust,simplifying rust book,web assembly with rust etc

**Comment by shaonkabir8** [comment]
Hi  mate :wave: 
Rust Programming Language cheat sheet has already added. I'm going to close this issue for now linking the valid pull request related to Rust. :heart:  
Our Contributors will contribute later on :boom: 
Stay connected with `Devsonket Family` :fire:
