### ISSUE TITLE
Json generator for easy contribution. 

### ISSUE THREAD

**Issue by shabab477** [devsonket/devsonket.github.io#53]
Right now it is very difficult to contribute to the repo because the contributor needs to write file in json format and then create a PR. This is not readable and makes it pretty hard to contribute. A json generator should be made in order to create json file from simple UI.

**Comment by iamruhul** [comment]
that can't be done in the frontend... You have to have some kinda backend for that!

**Comment by shabab477** [comment]
Not actually. What we have decided is something like json generator in which the contributor does not actually write JSON by himself/herself but by adding sections from the UI. Adding sections will result in real time JSON generation which can be downloaded client side. 

In the end the contributor has to contribute by a JSON file, but doesn't have to write the JSON manually.  It will be generated by the UI from the front end. 

Having a back end right now is not something that we want, maybe in the future.

**Comment by iamruhul** [comment]
brilliant!!!! Who's up for it??

**Comment by shabab477** [comment]
Right now I am working on this. Maybe within two weeks it will be done

**Comment by AnikHasibul** [comment]
> You have to have some kinda backend for that! 

I don't think so!

This can be implemented in native frontend ui with Javascript. I'm on it.

**Comment by zonayedpca** [comment]
This issue seems to be inactive for a long time. We're closing this one. Feel free to reopen this issue if you want... Thanks for being with us.
