### ISSUE TITLE
📃 Hacktoberfest 2021 নিয়ে আলোচনা 

### ISSUE THREAD

**Issue by shaonkabir8** [devsonket/devsonket.github.io#530]
অক্টোবর মাস জুড়েই চলবে `হ্যাক্টোবরফেস্ট উৎসব`  🔥 
বিগত সময়ের মত এবারও আমরা `ডেভসংকেত পরিবার` এই উৎসবে অংশগ্রহণ করবো।

আমাদের সকলের কন্ট্রিবিউশনে আরো সমৃদ্ধশালী হোক বাংলা ভাষার সবচেয়ে বড় চিটশিট ভান্ডার। 🚀

**Comment by zonayedpca** [comment]
ইয়েস ডেভসংকেত বরাবরের মতো এবারও থাকবে...

@shaonkabir8 আপনি রিডমি ফাইলে এটা অ্যানাউঞ্চ করে দিতে পারবেন কি একটু কষ্ট করে? কিভাবে অংশগ্রহণ করতে হবে সেটাও শর্ট করে একটু মেনশন করে দিবেন... ধন্যবাদ...

**Comment by sabbirshawon** [comment]
একমত @zonayedpca ভাই

**Comment by shaonkabir8** [comment]
@zonayedpca ধন্যবাদ ভাই।

আমি রিডমি ফাইলে এনাউন্সমেন্ট (কন্ট্রিবিউশন প্রোসেস সহ) দিয়ে দিচ্ছি। 🔥
