### ISSUE TITLE
Flutter.json এ ভুল ডেফিনেশন ও কোড

### ISSUE THREAD

**Issue by TasnimAnas** [devsonket/devsonket.github.io#542]
Flutter JSON ফাইলে (https://github.com/devsonket/devsonket.github.io/blob/develop/data/flutter.json) লাইন ২০-২১ ও ২৪-২৫ এ ভুল ডেফিনেশন ও কোড দেওয়া হয়েছে।

**Comment by shaonkabir8** [comment]
@TasnimAnas,
ভুলগুলো সংশোধন করে পুল রিকুয়েস্ট দেন। 🚀
