### ISSUE TITLE
Git emoji Cheatsheet যুক্ত করার পরেও এটা খুঁজে পাওয়া যাচ্ছে না ডেভসংকেত ওয়েব সাইটে

### ISSUE THREAD

**Issue by asifadib** [devsonket/devsonket.github.io#558]
স্ক্রিনশর্টগুলো দেখলে বুঝতে পারবেন 

![image](https://user-images.githubusercontent.com/45002778/135966060-862e4883-9f39-452b-a241-d101272a2a87.png)

![image](https://user-images.githubusercontent.com/45002778/135966151-7a5312dd-837a-4aec-84a8-fb5ea9199510.png)

**Comment by zonayedpca** [comment]
Sorry, we had one PR wrongly merged that was creating the issue, it should be live soon... Thanks for informing us... :)
