### ISSUE TITLE
সব কন্ট্রিবিউটারদের অবদান দৃশ্যমান থাকবে

### ISSUE THREAD

**Issue by zonayedpca** [devsonket/devsonket.github.io#56]
সবার কন্ট্রিবিউশন দৃশ্যমান থাকার লক্ষ্যেঃ 
- হোমপেজের একদম উপরেই প্রতি সপ্তাহে/মাসে টপ ৫ জন কন্ট্রিবিউটরের নাম তাদের গিটহাব প্রোফাইলসহ দেখানো
- সবার সুবিধা এবং উপকারের জন্য যে চিটশিটে যাদের অবদান(কন্ট্রিবিউশন) থাকবে, তাদের নামগুলো তাদের গিটহাব প্রোফাইলের লিঙ্কসহ উক্ত চিটশিটের পেজের একদম উপরে দেখানো...

**Comment by Hasnayeen** [comment]
You can use [Sourcerer.io](https://sourcerer.io/hasnayeen) to show contributors, I'm using it on my project.
You can check how it looks in my project [here](https://github.com/iluminar/goodwork#credits-top)

**Comment by shabab477** [comment]
Does `Sourceror.io` have a free or publicly accessible API that I can just piggy back on passing my repo id and user id? Would be great if this information was available.

**Comment by Hasnayeen** [comment]
You have to create an account to avail the widget, I used mine forked repo of this repository to build the widget which looks like this

[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/0)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/0)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/1)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/1)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/2)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/2)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/3)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/3)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/4)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/4)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/5)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/5)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/6)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/6)[![](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/images/7)](https://sourcerer.io/fame/Hasnayeen/Hasnayeen/devsonket.github.io/links/7)

**Comment by shabab477** [comment]
This is good but is the widget customizable? For example I want to show top 10 instead of top 7 contributors? If so then it should be ok. If not then we need to have a discussion regarding using this vs github api or something else.

**Comment by zonayedpca** [comment]
> সবার কন্ট্রিবিউশন দৃশ্যমান থাকার লক্ষ্যেঃ
> 
> * হোমপেজের একদম উপরেই প্রতি সপ্তাহে/মাসে টপ ৫ জন কন্ট্রিবিউটরের নাম তাদের গিটহাব প্রোফাইলসহ দেখানো
> * ~~সবার সুবিধা এবং উপকারের জন্য যে চিটশিটে যাদের অবদান(কন্ট্রিবিউশন) থাকবে, তাদের নামগুলো তাদের গিটহাব প্রোফাইলের লিঙ্কসহ উক্ত চিটশিটের পেজের একদম উপরে দেখানো...~~

এখান থেকে একটা কাজ করা হয়ে গেছে, Pull Request #72
