### ISSUE TITLE
প্রিন্ট শীটের স্টাইলিং এ সমস্যা 

### ISSUE THREAD

**Issue by zonayedpca** [devsonket/devsonket.github.io#57]
এখানে সবগুলো চিটশিটের প্রিন্ট ভার্শনও আছে... তবে এখানে একটা সমস্যা দেখতে পাচ্ছি... কিছু কিছু কার্ড এক পেজ থেকে আরেক পেজে ভাগ হয়ে যাচ্ছে... মাঝেমধ্যে কোড আর বর্ণনাও ভাগ হয়ে যাচ্ছে... এগুলো ফিক্স করা জরুরী... 
কার্ড ভাগ হয়ে যাওয়াঃ 
![image](https://user-images.githubusercontent.com/18544717/48972284-2d6bfd00-f04d-11e8-9c99-29516f6f7187.png)

কোড আর বর্ণনা ভাগ হয়ে যাওয়াঃ
![image](https://user-images.githubusercontent.com/18544717/48972291-4c6a8f00-f04d-11e8-9fc1-76759aa2a169.png)

**Comment by NaSabbir** [comment]
আমিও সমস্যা দেখতে পাচ্ছি, সমস্যার সমাধান দেখার প্রত্যাশায় রইলাম।
