### ISSUE TITLE
Redundant file shell.json

### ISSUE THREAD

**Issue by istiak101** [devsonket/devsonket.github.io#590]
Isn't shell.json redundant because it contains most of the commands from linux-command-line.json?

What would be more viable? Add more commands and split them into multiple cheatsheet or a single cheatsheet file?

https://github.com/devsonket/devsonket.github.io/blob/develop/data/linux-command-line.json
https://github.com/devsonket/devsonket.github.io/blob/develop/data/shell.json

**Comment by istiak101** [comment]
> I think both are separated? @istiak101

Yes both are separated but some of the contents are actually in both files.

**Comment by sabbirshawon** [comment]
> > I think both are separated? @istiak101
> 
> Yes both are separated but some of the contents are actually in both files.

Got it bro both are separated but most of the lines are same, I think if it will merge with both lines Then it will be okay @istiak101 or stay as it is.

**Comment by istiak101** [comment]
> Got it bro both are separated but most of the lines are same, I think if it will merge with both lines Then it will be okay @istiak101 or stay as it is.

Can you suggest an action? I am ok doing a PR if required.
