### ISSUE TITLE
Test for GA is Failing... 

### ISSUE THREAD

**Issue by zonayedpca** [devsonket/devsonket.github.io#63]
Google Analytics is failing during test...

**Comment by shabab477** [comment]
Please give a more descriptive issue post. The description should include the following points:
- Expected behavior
- Current behavior
- Steps to re-create the problem. 

Thanks.

**Comment by zonayedpca** [comment]
- Expected behavior ```npm run test``` should pass all the test 
- Current behavior: GA is removed to make sure travis ci can perform its task properly... But we want GA to be added as soon as it's fixed
- Step to Re-create the problem:
Run the test enabling GA on the project
```
npm run test
```
Will produce this error:
![image](https://user-images.githubusercontent.com/18544717/49011518-b2196100-f19c-11e8-88f3-4b4d41e0d04e.png)

Hope it will be fixed as soon as possible...

**Comment by shabab477** [comment]
![Pass screenshot](https://i.ibb.co/H4Q8VfK/app-pass.png)
