### ISSUE TITLE
পিএইচপি

### ISSUE THREAD

**Issue by rafiqul-rasel** [devsonket/devsonket.github.io#64]
পিএইচপি ফাংশন

**Comment by shabab477** [comment]
Sure, thanks for the interest. We currently have a cheat sheet regarding PHP [here](https://devsonket.github.io/php-cheat-sheet) where we have functions for number or string operations. Is there anything new you want to contribute to?

**Comment by rafiqul-rasel** [comment]
kivabe oi file korbo bolun??

**Comment by zonayedpca** [comment]
Closing this issue for not being active over a month
