### ISSUE TITLE
কিসের চিটশীট চান?

### ISSUE THREAD

**Issue by Programmer-anik** [devsonket/devsonket.github.io#655]
We need a javascript cheatsheet like others. It will be helpful fo me as well as  others

**Comment by zonayedpca** [comment]
জাভাস্ক্রিপ্ট নিয়ে বেশ কয়েকটা আছে, যেমন এটা একটাঃ https://devsonket.com/js-one-glance

আরো স্পেসিফিক কোনো বিষয়ের উপর যদি চান, তাহলে অবশ্যই রিকোয়েস্ট করবেন... ধন্যবাদ
