### ISSUE TITLE
CodeIgniter 4 চিট শীট

### ISSUE THREAD

**Issue by hafijul233** [devsonket/devsonket.github.io#689]
আমি CodeIgniter ফ্রেমওয়ার্ক সংস্করণ 4 চিটশিট অফার করতে চাই। 
এটি আগেরটির জন্য প্রায় পুনর্লিখিত আপগ্রেডেশন। পুরানো সিনট্যাক্স কাজ নাও করতে পারে যা বর্তমানে এই সাইটে প্রকাশিত হয়েছে।

**Comment by sabbirshawon** [comment]
ধন্যবাদ আপনি আগের টি চাইলে আপগ্রেড করতে পারেন অথবা নতুন কোডইগ্নিটর এ দিয়ে নতুন আরেকটি করতে পারেন @hafijul233
