### ISSUE TITLE
পাইথনের nltk মডিউলের চিটশিট

### ISSUE THREAD

**Issue by tahmid02016** [devsonket/devsonket.github.io#712]
আমি পাইথনের nltk মডিউলের উপরে একটি চিটশিট তৈরি করতে চাচ্ছি।

NLTK মডিউল ব্যবহার করে পাইথনে ন্যাচারাল ল্যাঙ্গুয়েজ প্রসেসিংয়ের কাজ করা হয়। মডিউল সম্পর্কে বিস্তারিত [এখানে](https://www.nltk.org/) পাওয়া যাবে।

**Comment by sabbirshawon** [comment]
চিটশিট এর ড্রাফট করে কাজ শুরু করে দিন।
