### ISSUE TITLE
Failed to load resource: the server responded with a status of 403 (Forbidden)

### ISSUE THREAD

**Issue by dibakarsutradhar** [devsonket/devsonket.github.io#77]
**Main Error** - **Failed to load resource: the server responded with a status of 403 (Forbidden)**

Error Message -
{
message: "API rate limit exceeded for 103.112.205.2. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)",
documentation_url: "https://developer.github.com/v3/#rate-limiting"
}

Error Link - https://api.github.com/repos/devsonket/devsonket.github.io/commits?path=data/shortcut-chrome-win.json

![image](https://user-images.githubusercontent.com/12207794/49147634-64812d80-f32f-11e8-9581-65d0cc3ef882.png)

**Comment by zonayedpca** [comment]
I will add some error handling technique so that the contribution data doesn't show up when GitHub API limit exceeds its limitation

**Comment by dibakarsutradhar** [comment]
Okay.

**Comment by zonayedpca** [comment]
We should observe the behavior of our Application as I am not able to recreate the same scenario. If you find the error again, please let us know. From now on, if GitHub API limit exceeds, the contributor section will not show up and the whole application will run normally...

**Comment by shabab477** [comment]
I think one way to recreate this issue is to refresh the page multiple times.

**Comment by shabab477** [comment]
I think the best solution should be to cache the last successful GitHub API call response and in the event of rate limit exceeded use the cached value.

**Comment by zonayedpca** [comment]
PR #81 handles the error, User will not experience any problem while visiting the website. I will cache the data in the next PR that will be a new feature for this application.

**Comment by dibakarsutradhar** [comment]
@zonayedpca I'm having the same problem again.

**Comment by zonayedpca** [comment]
Changes will take some time... You can use private/incognito mode to let us know if you still have the problem...

**Comment by dibakarsutradhar** [comment]
Having this problem on my windows machine and iPhone. Working fine on Linux machine though. Checked just now, it's working again. But the contribution section isn't there anymore though. 

![image](https://user-images.githubusercontent.com/12207794/49172649-d37c7780-f36b-11e8-887a-8eb1e3327f22.png)
