### ISSUE TITLE
C cheatsheet | প্রিমিটিভ ভ্যারিয়েবল টাইপ(ফ্লোট) wrong texts

### ISSUE THREAD

**Issue by 0xMahabub** [devsonket/devsonket.github.io#793]
![Screenshot from 2022-10-15 19-59-00](https://user-images.githubusercontent.com/86561283/195990475-d40d0a5b-265c-42fd-8d49-2b74e1e7af84.png)
Please correct this texts

**Comment by 0xMahabub** [comment]
@zonayedpca can I touch this?

**Comment by zonayedpca** [comment]
Yes definitely you can edit/modify/correct any cheatsheet data. Thanks

**Comment by 0xMahabub** [comment]
#794 plz  check this out
