### ISSUE TITLE
Favorite List

### ISSUE THREAD

**Issue by zonayedpca** [devsonket/devsonket.github.io#84]
I want to add a new functionality that will let a user add any cheatsheet as their favorite cheatsheet. And they will be shown in the TOP section in which we have some static top cheatsheet right now(also used to display search result). If the user's favorite list is empty, then the TOP section will display our selected list. Otherwise, It will show the user's favorite list... Is it necessary? What do you think?

**Comment by dibakarsutradhar** [comment]
It’ll be a good addition to the project

**Comment by iamruhul** [comment]
First of all... what's the reason of those color cards at the top??

**Comment by zonayedpca** [comment]
Closing this issue for not being active over a month
