### ISSUE TITLE
NestJS framework @New Cheat-sheet 

### ISSUE THREAD

**Issue by 0xMahabub** [devsonket/devsonket.github.io#841]
**NestJS** is a progressive nodejs based (uses TypeScript) backend framework built on the top of expressJs and fastify too. It is also called backend for angular developers.
I would like to make a new cheatsheet about it [**NEW**]
Others are also invited :)

**Comment by HridoyHazard** [comment]
here is the pr #864

**Comment by 0xMahabub** [comment]
> here is the pr #864

It's done ✅
