### ISSUE TITLE
কিসের চিটশীট চান?

### ISSUE THREAD

**Issue by MDJAHID-DEV** [devsonket/devsonket.github.io#964]
I wan't a cheat sheet on javascript, typescript I have not touched boostrap or tailwaind css if its possible to create cheat sheet it will be great for beginners and expert programmers

**Comment by rahulmangla28** [comment]
Please assign this issue to me.

**Comment by shaonkabir8** [comment]
প্রয়োজনীয় `টপিক` ছাড়া `ইস্যু` এবং একই নামের একাধিক `ইস্যু` না তৈরী করার জন্য অনুরোধ করছি। 

ধন্যবাদ।
