### ISSUE TITLE
কিসের চিটশীট চান?

### ISSUE THREAD

**Issue by rumon5h** [devsonket/devsonket.github.io#999]
কি কি চান বিস্তারিত লিখুন

- property
- attribute

**Comment by rumon5h** [comment]
Add more topics

**Comment by shaonkabir8** [comment]
প্রয়োজনীয় `টপিক` ছাড়া `ইস্যু` এবং একই নামের একাধিক `ইস্যু` না তৈরী করার জন্য অনুরোধ করছি। 

ধন্যবাদ।
